INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Pistolancier", "Guerrier",)
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES(Berserker, "Guerrier")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Paladin", "Guerrier")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Elementiste", "Martialiste")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Essentialiste""Martialiste")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Spirite", "Martialiste")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Pugiliste", "Martialiste")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Franc-Tireur", "Tireur d'elite")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Fusiliere", "Tireur d'elite")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Sagitaire", "Tireur d'elite")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Artilleur", "Tireur d'elite")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Sorcière", "Mage")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Barde", "Mage")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Sanguelame", "Assassin")
INSERT INTO SubClass(name, archetype, engraving1, engraving2, characteristic1, characteristic2, optimization) VALUES("Démoniste", "Assassin")