INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Pistolancier', 'Guerrier', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Berserker', 'Guerrier', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Paladin', 'Guerrier', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Elementiste', 'Martialiste', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Essentialiste', 'Martialiste', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Spirite', 'Martialiste', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Pugiliste', 'Martialiste', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Franc-Tireur', 'Tireur d''élite', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Fusiliere', 'Tireur d''elite', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Sagitaire', 'Tireur d''elite', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Artilleur', 'Tireur d''elite', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Sorcière', 'Mage', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Barde', 'Mage', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Sanguelame', 'Assassin', 'a', 'a', 'a', 'a', 'a');
INSERT INTO SUB_CLASS(name, archetype, engraving1, engraving2, characteristic1, characteristic2, specialization) VALUES('Démoniste', 'Assassin', 'a', 'a', 'a', 'a', 'a');