package com.projetperso.projectlostark.utils;

public enum Engravings {
    AMELIORATION_D_ETHER("Amélioration d'éther"),
    ARME_AFFUTEE("Arme affûtée"),
    AUGMENTATION_DES_PM_MAX("Augmentation des PM max"),
    BAGAREUR_EXPERT("Bagarreur expert"),
    BARRICADE("Barricade"),
    BOUCLIER_AMELIORE(""),
    CAPITAINE_DE_RAID("Capitaine de raid"),
    CAPTURE_D_AME("Capture d'âme"),
    CHARGE_LOURDE("Charge lourde"),
    CONCURRENT("Concurrent"),
    DETERMINATION("Détermination"),
    EQUILIBRE("Equilibre"),
    EQUIPEMENT_D_ARMURE_LOURDE("Equipement d'armure lourde"),
    EVASION_CRITIQUE("Evasion critique"),
    EVEIL("Eveil"),
    EXPERT_EN_EXPLOSIFS("Expert en explosifs"),
    FLUX_DE_MAGIE("Flux de magie"),
    FORCE_D_AME("Force d'âme"),
    FRACTURE("Fracture"),
    FRAPPE_AUX_POINTS_VITAUX("Frappe aux points vitaux"),
    FRAPPE_PREVENTIVE("Frappe préventive"),
    FURIE_FOUDROYANTE("Furie foudroyante"),
    GOUTTES_D_ETHER("Gouttes d'éther"),
    IRREVERENCE("Irrévérence"),
    MAITRE_DE_L_EMBUSCADE("Maître de l'embuscade"),
    MAITRE_DE_L_EVASION("Maître de l'évasion"),
    NECROMANCIE("Nécromancie"),
    PERCAGE_DE_BOUCLIER("Perçage de bouclier"),
    POING_ECRASANT("Poing écrasant"),
    POUPEE_MAUDITE("Poupée maudite"),
    PROTECTION_DIVINE("Protection divine"),
    RETOUR_DE_FLAMME("Retour de flamme"),
    REGENERATION_DE_PM("Régénération de PM+"),
    TENACITE_INVAINCUE("Ténacité invaincue"),
    A(""),
    B(""),
    C(""),
    D(""),
    E(""),
    F(""),
    G(""),
    H(""),
    I(""),
    J(""),
    K(""),
    L(""),
    M(""),
    N(""),
    O(""),
    P(""),
    Q(""),
    R(""),
    S(""),
    T(""),
    U(""),
    V(""),
    W(""),
    X(""),
    Y(""),
    Z("");

    final String engravingName;

    Engravings(String engravingName) {
        this.engravingName = engravingName;
    }
}